### ISSUE TITLE
Problems when Home Assistant started when bulbs are offline

### ISSUE THREAD

**Issue by jarpatus** [sbidy/wiz_light#98] opened 2021-02-01 21:21 UTC
Noticed that v0.3 has been released and decided to try it. Upgraded to latest home assistant, pywizlight and wiz_light. Commented out my old wiz_light configuration and added one test bulb via Home Assistant. So far so good, but then I took my test bulb offline and restarted Home Assistant. As a result Home Assistant tries to connect to now offline bulb and since it is not answering this will eventually timeout:

2021-02-01 23:03:53 ERROR (MainThread) [pywizlight.bulb] [wizlight 172.16.50.9, connid 3946fed8370c80] Failed to do UDP call(s) to wiz light - Timeout Error!

Until timeout happens, this will block dashboards etc. This effectively makes doing customizations and complex configurations very hard due to long startup delay. One could try to keep all bulbs online when starting Home Assistant, but when you have dozens of bulbs this may not be possible.

After Home Assistant starts, another problem arises:

![image](https://user-images.githubusercontent.com/1280811/106519129-85cb9e80-64e3-11eb-9fc7-f1d589e5a20c.png)

![image](https://user-images.githubusercontent.com/1280811/106519204-a09e1300-64e3-11eb-9683-b81b8b0e7572.png)

So bulb has now been cloned. If I turn on the bulb, Home Assistant will see the clone (light.wiz_73437e_2), not the initial one and none of the automations do work. Not sure if the cloning stuff is due to some custom automations though.

v0.2 release did not suffer from any of this so at the moment I have to restore previous version. Sadly I do not know Home Assistant well enough in order to try to contribute with fixes :(

**Comment by sbidy** [comment] 2021-02-01 21:40
Yes, that's correct. If you startup the HASS and the bulbs are offline (switched physically off) this error shows up and the bulbs are remaining in the offline sate. I can reproduce the issue and try to fix it.

I think this can be a correlation issue with the HASS statup sequece. Because I you startup the HASS with the bulb online all looks fine. And if you then switch the bulb to offline the update poll will work (HASS tries to connect to the bulb every 15 secs.).

**Comment by sbidy** [comment] 2021-02-01 21:46
Possible fix - https://github.com/sbidy/wiz_light/commit/3c14ccea8bee16c2820d2a9957cfbb39a0a2c29b

**Comment by sbidy** [comment] 2021-02-01 21:51
Seems to be a error in the lib - https://github.com/sbidy/pywizlight/issues/42

**Comment by sbidy** [comment] 2021-02-03 21:53
This should be fixed with the 0.3.1 version.
Maybe you can test with this version again.

Thank you!

**Comment by jarpatus** [comment] 2021-02-04 16:30
I tested this out. Not sure if I am doing something wrong, but does not seem to change much. No longer I can see timeout error in the log, but starting up home assistant will take a long time and bulbs offline when home assistant is started will get duplicated:

![image](https://user-images.githubusercontent.com/1280811/106923387-acbde680-6716-11eb-9078-5f4976371060.png)

I am using hassistant 2021.1.5, pywizlight 0.4.4 and wiz_light 0.3.1.

**Comment by jarpatus** [comment] 2021-02-04 16:52
I enabled debug logging for pywizlight and I can see following when home assistant is starting it tries to connect to the bulb:

2021-02-04 18:44:04 DEBUG (MainThread) [custom_components.wiz_light] Get bulb with IP: 172.16.50.13
2021-02-04 18:44:04 DEBUG (MainThread) [pywizlight.bulb] [wizlight 172.16.50.13, connid 3949361d747e86] connecting to UDP port with send_interval of 0.5 sec..
2021-02-04 18:44:04 DEBUG (MainThread) [pywizlight.bulb] [wizlight 172.16.50.13, connid 3949361d747e86] listening for response datagram
2021-02-04 18:44:04 DEBUG (MainThread) [pywizlight.bulb] [wizlight 172.16.50.13, connid 3949361d747e86] sending command datagram 0: {"method":"getPilot","params":{}}
2021-02-04 18:44:04 DEBUG (MainThread) [pywizlight.bulb] [wizlight 172.16.50.13, connid 3949361d747e86] sending command datagram 1: {"method":"getPilot","params":{}}
2021-02-04 18:44:05 DEBUG (MainThread) [pywizlight.bulb] [wizlight 172.16.50.13, connid 3949361d747e86] sending command datagram 2: {"method":"getPilot","params":{}}
2021-02-04 18:44:05 DEBUG (MainThread) [pywizlight.bulb] [wizlight 172.16.50.13, connid 3949361d747e86] sending command datagram 3: {"method":"getPilot","params":{}}
2021-02-04 18:44:06 DEBUG (MainThread) [pywizlight.bulb] [wizlight 172.16.50.13, connid 3949361d747e86] sending command datagram 4: {"method":"getPilot","params":{}}
2021-02-04 18:44:06 DEBUG (MainThread) [pywizlight.bulb] [wizlight 172.16.50.13, connid 3949361d747e86] sending command datagram 5: {"method":"getPilot","params":{}}
2021-02-04 18:44:07 DEBUG (MainThread) [pywizlight.bulb] [wizlight 172.16.50.13, connid 3949361d747e86] sending command datagram 6: {"method":"getPilot","params":{}}
2021-02-04 18:44:07 DEBUG (MainThread) [pywizlight.bulb] [wizlight 172.16.50.13, connid 3949361d747e86] sending command datagram 7: {"method":"getPilot","params":{}}
2021-02-04 18:44:08 DEBUG (MainThread) [pywizlight.bulb] [wizlight 172.16.50.13, connid 3949361d747e86] sending command datagram 8: {"method":"getPilot","params":{}}
2021-02-04 18:44:08 DEBUG (MainThread) [pywizlight.bulb] [wizlight 172.16.50.13, connid 3949361d747e86] sending command datagram 9: {"method":"getPilot","params":{}}
2021-02-04 18:44:14 DEBUG (MainThread) [pywizlight.bulb] [wizlight 172.16.50.13, connid 3949361d747e86] Failed to do UDP call(s) to wiz light - Timeout Error!
2021-02-04 18:44:14 DEBUG (MainThread) [custom_components.wiz_light.light] The request to the bulb timed out
2021-02-04 18:44:14 DEBUG (MainThread) [custom_components.wiz_light.light] [wizlight 172.16.50.13] updated state: False
2021-02-04 18:44:14 DEBUG (MainThread) [pywizlight.bulb] [wizlight 172.16.50.13, connid 394936236c098a] connecting to UDP port with send_interval of 0.5 sec..
2021-02-04 18:44:14 DEBUG (MainThread) [pywizlight.bulb] [wizlight 172.16.50.13, connid 394936236c098a] listening for response datagram
2021-02-04 18:44:14 DEBUG (MainThread) [pywizlight.bulb] [wizlight 172.16.50.13, connid 394936236c098a] sending command datagram 0: {"method":"getSystemConfig","params":{}}
2021-02-04 18:44:14 DEBUG (MainThread) [pywizlight.bulb] [wizlight 172.16.50.13, connid 394936236c098a] sending command datagram 1: {"method":"getSystemConfig","params":{}}
2021-02-04 18:44:15 DEBUG (MainThread) [pywizlight.bulb] [wizlight 172.16.50.13, connid 394936236c098a] sending command datagram 2: {"method":"getSystemConfig","params":{}}
2021-02-04 18:44:15 DEBUG (MainThread) [pywizlight.bulb] [wizlight 172.16.50.13, connid 394936236c098a] sending command datagram 3: {"method":"getSystemConfig","params":{}}
2021-02-04 18:44:16 DEBUG (MainThread) [pywizlight.bulb] [wizlight 172.16.50.13, connid 394936236c098a] sending command datagram 4: {"method":"getSystemConfig","params":{}}
2021-02-04 18:44:16 DEBUG (MainThread) [pywizlight.bulb] [wizlight 172.16.50.13, connid 394936236c098a] sending command datagram 5: {"method":"getSystemConfig","params":{}}
2021-02-04 18:44:17 DEBUG (MainThread) [pywizlight.bulb] [wizlight 172.16.50.13, connid 394936236c098a] sending command datagram 6: {"method":"getSystemConfig","params":{}}
2021-02-04 18:44:17 DEBUG (MainThread) [pywizlight.bulb] [wizlight 172.16.50.13, connid 394936236c098a] sending command datagram 7: {"method":"getSystemConfig","params":{}}
2021-02-04 18:44:18 DEBUG (MainThread) [pywizlight.bulb] [wizlight 172.16.50.13, connid 394936236c098a] sending command datagram 8: {"method":"getSystemConfig","params":{}}
2021-02-04 18:44:18 DEBUG (MainThread) [pywizlight.bulb] [wizlight 172.16.50.13, connid 394936236c098a] sending command datagram 9: {"method":"getSystemConfig","params":{}}
2021-02-04 18:44:24 DEBUG (MainThread) [pywizlight.bulb] [wizlight 172.16.50.13, connid 394936236c098a] Failed to do UDP call(s) to wiz light - Timeout Error!
2021-02-04 18:44:24 DEBUG (MainThread) [custom_components.wiz_light.light] [wizlight 172.16.50.13] Bulbtype update failed - Timeout
2021-02-04 18:44:24 DEBUG (MainThread) [pywizlight.bulb] [wizlight 172.16.50.13, connid 39493629628ee0] connecting to UDP port with send_interval of 0.5 sec..
2021-02-04 18:44:24 DEBUG (MainThread) [pywizlight.bulb] [wizlight 172.16.50.13, connid 39493629628ee0] listening for response datagram
2021-02-04 18:44:24 DEBUG (MainThread) [pywizlight.bulb] [wizlight 172.16.50.13, connid 39493629628ee0] sending command datagram 0: {"method":"getSystemConfig","params":{}}
2021-02-04 18:44:24 DEBUG (MainThread) [pywizlight.bulb] [wizlight 172.16.50.13, connid 39493629628ee0] sending command datagram 1: {"method":"getSystemConfig","params":{}}
2021-02-04 18:44:25 DEBUG (MainThread) [pywizlight.bulb] [wizlight 172.16.50.13, connid 39493629628ee0] sending command datagram 2: {"method":"getSystemConfig","params":{}}
2021-02-04 18:44:25 DEBUG (MainThread) [pywizlight.bulb] [wizlight 172.16.50.13, connid 39493629628ee0] sending command datagram 3: {"method":"getSystemConfig","params":{}}
2021-02-04 18:44:26 DEBUG (MainThread) [pywizlight.bulb] [wizlight 172.16.50.13, connid 39493629628ee0] sending command datagram 4: {"method":"getSystemConfig","params":{}}
2021-02-04 18:44:26 DEBUG (MainThread) [pywizlight.bulb] [wizlight 172.16.50.13, connid 39493629628ee0] sending command datagram 5: {"method":"getSystemConfig","params":{}}
2021-02-04 18:44:27 DEBUG (MainThread) [pywizlight.bulb] [wizlight 172.16.50.13, connid 39493629628ee0] sending command datagram 6: {"method":"getSystemConfig","params":{}}
2021-02-04 18:44:27 DEBUG (MainThread) [pywizlight.bulb] [wizlight 172.16.50.13, connid 39493629628ee0] sending command datagram 7: {"method":"getSystemConfig","params":{}}
2021-02-04 18:44:28 DEBUG (MainThread) [pywizlight.bulb] [wizlight 172.16.50.13, connid 39493629628ee0] sending command datagram 8: {"method":"getSystemConfig","params":{}}
2021-02-04 18:44:28 DEBUG (MainThread) [pywizlight.bulb] [wizlight 172.16.50.13, connid 39493629628ee0] sending command datagram 9: {"method":"getSystemConfig","params":{}}
2021-02-04 18:44:34 DEBUG (MainThread) [pywizlight.bulb] [wizlight 172.16.50.13, connid 39493629628ee0] Failed to do UDP call(s) to wiz light - Timeout Error!
2021-02-04 18:44:34 DEBUG (MainThread) [custom_components.wiz_light.light] [wizlight 172.16.50.13] Mac update failed - Timeout

After last row (mac update failed) home assistant fully starts up and I can see duplicate bulbs. I do not know software architecture of home assistant so it could be possible that architecture demands connecting to the integrated device on start and this will block startup until timeout no matter what? At least Ikea Trådfri integration does the same - if Trådfri gateway is offline than it will block until timeout. This is mildly annyoing with Trådfri but not a problem since Trådfri gateway usually is up 99.99% of time even though lights could be down. But in case of WiZ integration each bulbs is it's own integration (if I understood this right) and if startup will be blocked if any of the bulbs are offline then itäs going to be major problem. Just my 5 cents, not sure if 0.3.1 was supposed to change this :)

**Comment by jarpatus** [comment] 2021-02-05 17:04
Oh, quick update. v0.3.1 may have fied this bulb duplication issue. I was using .homeassistant folder from v0.3 and it may have contained some entities in the database or something... I did clean up all "restored" entities and now v0.3.1 seems NOT to duplicate bulbs anymore even if bulbs are offline when home assistant is started.

Offline bulbs do still block startup, but that is not show stopper.

**Comment by sbidy** [comment] 2021-02-08 22:06
I can't reproduce this duplication problem with by testing and prod HASS.
There are major changes between the 0.2. and 0.3 regarding adding the bulbs. An duplicated entry is basically not possible because I use the MAC of the bulb a unique identifier. Can you please check if you have added the bulb via `configuration.ymal` and via UI twice? Please also remove all bulbs from the YAML an add these via UI. The YAML file will be deprecated in the future.
Can you please share your entities list? What are the IDs of these bulbs?

There are an issue on older HASS versions with startup latency if bulbs or other devices are offline. Please check your HASS version and my update to the latest build. This should fix the startup blocking but at the end this delay of 30sec will never fixed because of the UDP connection. The integration has to try multiple times before a "real" timeout can be returned. In some cases the bulb maybe have bad WIFi connection etc. But I'll ask the HASS dev community for advice may I can reduce this to 10 sec. in the future. UDP is a really bad "protocol" because you get no feedback/acknowledgement - it is "fire and forget".  And add this on top of a non reliable WiFi connection to small bulbs 😉

**Comment by sbidy** [comment] 2021-02-10 20:34
Please also consider to update to the wiz_light version 0.4.

**Comment by jarpatus** [comment] 2021-02-13 07:12
Ok I did set up separate home assistant development environment so I can more liberally test things out without worrying about breaking lights of my whole house. So this is vanilla home assistant instalation:

Home assistant version: core-2021.2.3
Python version: 3.8.7
pywizlight version:  0.4.5
wiz_light version: 0.4.0 (release tgz, not github pull)

I started home assistant and added one WiZ bulb (using config flow or whatever it is called, I did not touch configuration.yaml). Everything works. I did shut down home assistant, took bulb offline (by offline I mean I did cut mains power from the bulb, I will be using word offline and online from here on meaning this) and started home assistant. After home assistant has been started, I can see my test bulb duplicated:

![image](https://user-images.githubusercontent.com/1280811/107844347-3dfa2080-6ddb-11eb-9437-9d40a09cd62b.png)

Entities:

![image](https://user-images.githubusercontent.com/1280811/107844355-4ce0d300-6ddb-11eb-82ab-dfad3b876e96.png)

Devices (no duplicates):

![image](https://user-images.githubusercontent.com/1280811/107844362-59652b80-6ddb-11eb-8538-17dad7bc9a51.png)

**Comment by sbidy** [comment] 2021-02-14 17:30
I'm working on that.
If the bulb is offline at startup, HASS will never bring the bulb in the state available. Regardless if the bulb is switched on after startup. Currently the workaround is to connect all bulb to power on startup.

It seems to be an issue with the HASS core because my integration will report the correct state in the `available` property. But if the bulb is offline at startup HASS flags this as "removed".

**Comment by excalbian** [comment] 2021-02-22 16:21
@sbidy Does this also explain the `light.light_wiz_733df4_2` entity that is getting created? I'm seeing since upgrading to 0.4.0 (and today on `master`) that when a bulb that was offline (no power) at home assistant startup becomes available, the new entity (`_2`) is created (and then will stay into the next restart, breaking automations 😿).

**Comment by sbidy** [comment] 2021-02-22 17:14
Yes, it is bigger issue because it is hard to debug this with the HASS stack. Unfortunately the HASS doc is also not really accurate about that behavoiur. I try it to get some insights and ideas from the office dev-discord but with no luck.
On top of that I can't reproduce this issue with my tow physical bulb here. I can reproduce the issue that the bulb will stay offline if offline on startup but the duplication doesn't occur.

So I have to digging in to that deeper but this takes some time ... I'll try to fix this in the next days. Stay tuned!

**Comment by eminphi** [comment] 2021-10-05 00:23
Any update on this issue? I am having the exact same duplicate entity behavior with my Phillips downlights.

**Comment by sbidy** [comment] 2021-10-05 07:34
There are some ideas from the HASS community. Maybe the one of them will bring the fix for that issue.
But I have to check that first make several tests which is really difficult and takes some time.

I was a bit offline the last weeks but I will have a look into that topic as soon as possible 😉

**Comment by bram-pkg** [comment] 2021-10-06 08:55
Thanks man!

**Comment by sphbecker** [comment] 2021-12-13 20:44
Thanks for all your work on this! Loving the possibilities this project brings to the table! Just wondering if there is an easy way to return the lights to normal status when this issue occurs. The only thing I found that works is (after deleting the duplicates) click on each Integration and choose "Reload". It works, but with 26 bulbs that is kind of a click-fest. Is there an easy to get all of them to reload at the same time?

**Comment by bdraco** [comment] 2022-02-15 20:35
This can be closed as its fixed in the core version

**Closed** 2022-02-15 21:22 UTC
Labels: Bug
