### ISSUE TITLE
Light groups don't work

### ISSUE THREAD

**Issue by ralong777** [sbidy/wiz_light#173] opened 2021-09-26 10:24 UTC
I’m trying to make my first light group and cant make it to work.
The light group is always unavailable

im running the latest version of wiz integration and home assistant on Raspbian in docker.

https://community.home-assistant.io/t/light-groups-dont-work/341671

**Comment by sbidy** [comment] 2021-10-05 07:07
Ah, please try to add one or two bulbs via the UI wizard. The error message from your forum post seems to come from the missing "entity_id" and without this id HASS can not add these bulbs to a group.

**Comment by ralong777** [comment] 2021-10-05 16:41
Where/what is the UI wizzard?

**Comment by sjee** [comment] 2021-10-16 20:45
I had similar errors when I had 2 lights and one switch/socket in my _configuration.xml_ and then later added them via the ui wizard. 

The reason for that was that I initially added all my lights in _configuration.xml_ before the ui wizard was available. At some point I lost control over certain lights in HA. 

_(Turns out this was related to my Wiz bulbs and the Wiz switch having **new** IP  addresses assigned by my modemrouter. So, there was a mismatch with the IP addresses in the config file.)_ 

But by then the ui wizard was available and I had added them to HA again via the ui.  The errors went away when I removed those lights and switch from the configuration file.

Note though, that in my case the the lights and the switch were accessible despite the logged errors.

> I tried this. It still doesnt work. but i have this in the logs:
> 
> ```
> Logger: homeassistant.components.light
> Source: helpers/entity_platform.py:566
> Integration: Light (documentation, issues)
> First occurred: 10:03:43 (3 occurrences)
> Last logged: 10:03:44
> 
> Platform wiz_light does not generate unique IDs. ID a8bb50fab551 already exists - ignoring light.light_kitchen
> Platform wiz_light does not generate unique IDs. ID a8bb50bb1ec4 already exists - ignoring light.light_hall
> Platform wiz_light does not generate unique IDs. ID a8bb50faa295 already exists - ignoring light.light_bed_center
> ```

**Comment by sjee** [comment] 2021-10-16 21:32
Have you tried using `name: "All Lights` in the configuration? That should make it accessible as an entity called `light.all_lights`

_(BTW: None of my names contain periods or underscores.)_

**Comment by ralong777** [comment] 2021-10-16 21:48
Yes i tried different names. No change

**Comment by ScottG489** [comment] 2021-11-10 18:21
I'm adding this into this card because of the ambiguous/broad title, but I am also observing an issue with groups.

I have a group of two lights (same Wiz model). When in the light group dialog window, the temperature will always display as 153 (all the way far left, pure white?) no matter what I set it to last.

Perhaps related to #172?

**Comment by sbidy** [comment] 2021-11-11 09:40
Seems to be an issue with groups and scenes in HASS.
I'm working on it.

**Comment by sbidy** [comment] 2021-11-16 23:02
I think this #172 and #177 are related.

I have tested it with an older and the current version of HASS and I can't reproduce the issue. In case of IP address changes (expired leasetimes) there can reside some "zombie" entries.

So please make the following step
1. Please delete all bulbs (devices and entries) // If you have multiple bulbs, please test with 2 or 3 first 😉 
2. Ensure that you are using the latest version of the wiz_light integration
3. Restart HASS - Keep in mind that all bulbs should be connected to the power while restarting HASS
4. Re-Add the bulbs with the DNS name wiz-<last 6 digits from the MAC> - you can find the MAC in the WiZ app by hitting in the settings on the "Model" text. This will prevent an issue in case of an IP address change.
5. The bulbs should be added as device and entry

Hope this helps....

**Comment by RaptorPR443** [comment] 2021-12-16 22:39
you can assign light groups in the config yaml for the wiz lights i have been using this for months and no issue so far:

light:
  - platform: group
    name: (name of the group)
    entities:
      - light.wiz_(last 6 mac adr digits)

you can continue to add as many wiz lights to the group as you like or if you need more groups copy starting from platform and paste ad add as needed.

**Comment by ralong777** [comment] 2021-12-16 23:42
IN my first post i wrote that this doesnt work for me. Check the link

**Comment by quielb** [comment] 2021-12-20 01:43
@ralong777  I've added a comment on your original HA forums post that will fix your issue. You have an error in your entity definitions. Please refer to your original HA forums post for the solution.

**Comment by bdraco** [comment] 2022-02-15 20:36
This can be closed as its confirmed working in the core version

**Closed** 2022-02-15 21:20 UTC
Labels: Bug
