### ISSUE TITLE
HA Icon Color Doesn't Update When Applying Effect

### ISSUE THREAD

**Issue by austinbeam** [sbidy/wiz_light#145] opened 2021-05-22 05:15 UTC
Hello,
Thanks for all the hard work on this. I'm noticing that the integration doesn't seem to reflect the bulb color when applying an effect. This is a bit frustrating because whatever color was previously applied will color the icon in HA. Is it possible to have the color sync when an effect is applied?

Steps to reproduce:
- Apply a color (say, green) to a bulb
- Apply the "Warm White" effect
- Note that the icon stays green while the bulb changes to "Warm White" as instructed

Thanks again for all the hard work -- have a good one.

**Comment by sbidy** [comment] 2021-05-26 05:18
That's not possible to update the color from a effect. The Bild does not return a color value.

**Comment by MFuell2** [comment] 2021-09-15 17:18
Loving this so far!!
I am also having this issue, but the issue is deeper than just visuals. (using ~18 RGB + tunable white bulbs)
Setting the bulb to say, green will change the bulb to green, and then using the white slider will change the bulb to a given white temp, but the icon stays green, and the true color mode of the bulb stays "hs" instead of changing back to "color_temp".

Changing the bulbs to a white, and then restarting HASS fixes it until another color is used.

This impacts the color of the icon, as well as the color wheel/ white tab that appears when clicking on the bulb entity from the dashboard.
I think this should be changed to bug, unless this is fully covered in another bug report.

Thanks!!

**Comment by sbidy** [comment] 2021-12-16 21:35
Should be fixed in 0.4.5

**Comment by bdraco** [comment] 2022-02-15 20:33
This can be closed as its fixed in the core version

**Closed** 2022-02-15 21:21 UTC
Labels: enhancement, question, wontfix
