### ISSUE TITLE
Wiz Bulbs Stuck in Color Mode

### ISSUE THREAD

**Issue by MFuell2** [sbidy/wiz_light#172] opened 2021-09-16 16:01 UTC
Loving this so far!!
(using ~18 RGB + tunable white bulbs)
Setting the bulb to say, green will change the bulb to green, and then using the white slider will change the bulb to a given white temp, but the icon stays green, and the color mode of the bulb stays `hs` instead of changing back to `color_temp`.

The bulb correctly updates to the new colors and to the temps, at least to my eye, and the Wiz app shows that it is a white temperature, however the color wheel/white slider menu does not behave as it should.

Steps to replicate:
1. Start Home Assistant
2. Change a bulb to a color (green in this case)
3. Change the bulb to a white color using the temp slider
4. Click off of the bulb card
5. Click back to the bulb card, and the bulb card will take you straight to the color menu, and not the white menu
(included images below showing the state of the bulbs)

Changing the bulbs to a white, and then restarting HASS fixes it temporarily until another color is used.

Thanks!!

Also mentioned here, but not directly acknowledged or properly explained:
https://github.com/sbidy/wiz_light/issues/145#issuecomment-920214795
https://github.com/sbidy/wiz_light/issues/80#issuecomment-835880109

Starting point: bulb is starting in white mode
![image](https://user-images.githubusercontent.com/67154905/133643603-3d5c9758-6db7-4d3f-b12a-a1159c0ce8f4.png)
![image](https://user-images.githubusercontent.com/67154905/133643910-112f9667-2390-4d56-ac20-d91277dc041a.png)
![image](https://user-images.githubusercontent.com/67154905/133643965-ed0a6b57-843b-42d2-a5ad-527d5765d4e9.png)

Changing to Green:
![image](https://user-images.githubusercontent.com/67154905/133644149-716d057a-51cf-4394-8406-3f41493a75a4.png)
![image](https://user-images.githubusercontent.com/67154905/133644362-6be541be-8b0e-4a40-82cc-cc0e233ad07c.png)

Changing to Red:
![image](https://user-images.githubusercontent.com/67154905/133644548-1025cb6f-abd5-478c-9d44-7dc052fca886.png)
![image](https://user-images.githubusercontent.com/67154905/133644657-fc6cc237-d3c9-4ddd-8b54-6aa6849121c8.png)

Changing to white:
![image](https://user-images.githubusercontent.com/67154905/133644782-0f7dc14a-19cf-41cd-b63f-9cc322c7db4e.png)
![image](https://user-images.githubusercontent.com/67154905/133644979-c0128411-37eb-4949-aaae-708f9b0c72ec.png)

Clicking off the card, and back onto the card brings the color wheel up:
![image](https://user-images.githubusercontent.com/67154905/133645068-ac381ed1-7a2d-44bd-b2c3-cfac5803bd07.png)

**Comment by sbidy** [comment] 2021-10-05 07:03
Let me check this. But I'm sure that the status will not be rested after changing from color to color temp.

**Comment by ScottG489** [comment] 2021-11-10 18:10
I have this issue as well I believe.

Comparing it to another bulb I have (TP-Link Kasa bulb), the behavior there is:
1. Open the light dialog window
2. Change the color
3. Close then reopen the light dialog
4. Observe the color picker being selected
5. Change to the temperature picker
6. Change the temperature
7. Close then reopen the light dialog
8. Observe the temperature picker being selected

In other words, between the color and temperature picker, the last one you interacted with will be what displays when you open the dialog back up. This aligns with what behavior I would expect as well.

However, with the Wiz bulb, I had touched the color picker at one point and now it doesn't matter what I interacted with last, it always shows the color picker when I open up the light dialog window.

Also if I do choose a color and then change the temperature, the color picker still shows the previous color as selected and the bulb icon is that color as well.

@sbidy Also want to say thanks for your work on this project!

**Comment by vdheijden** [comment] 2021-12-01 00:49
I'm having the same issue.  I think it has to do with the "color_mode" state attribute.  Notice in MFuell2's screenshots, the color mode starts as "color_temp" and changes to "hs" when the color is changed.  This is correct so far.  The problem is, when the light is changed back to white via the temperature slider, the color_mode stays as "hs."  Instead, color_mode should change back to "color_temp."  I believe this is what drives the UI behavior.

I've done the same test on my Kasa bulb for comparison, and the color_mode correctly changes back and forth whereas the wiz bulb gets stuck in "hs" and never changes back.

**Comment by sbidy** [comment] 2021-12-16 21:36
Should be fixed in 0.4.5

**Comment by vdheijden** [comment] 2021-12-17 19:13
Tested and looks like it's working now.  Great work!

**Comment by bdraco** [comment] 2022-02-15 20:36
This can be closed as its confirmed fixed in the core version

**Closed** 2022-02-15 21:20 UTC
Labels: Bug, fixed but in review
