### ISSUE TITLE
ConnectionRefusedError appears in log when there are tasks waiting on light state changes

### ISSUE THREAD

**Issue by emichael** [sbidy/wiz_light#152] opened 2021-06-21 19:13 UTC
I'm getting the following error quite a bit in my logs whenever I have tasks that are trying to read the state of lights in RGB mode. The Dashboard UI also hangs for five or ten seconds, but eventually my automations complete successfully and do the right thing.

```
Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:97
First occurred: 12:02:52 PM (3 occurrences)
Last logged: 12:03:38 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/asyncio_dgram/aio.py", line 132, in send
    await super().send(data)
  File "/usr/local/lib/python3.8/site-packages/asyncio_dgram/aio.py", line 94, in send
    _ = self.exception
  File "/usr/local/lib/python3.8/site-packages/asyncio_dgram/aio.py", line 52, in exception
    raise exc
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 1011, in _read_ready
    data, addr = self._sock.recvfrom(self.max_size)
ConnectionRefusedError: [Errno 111] Connection refused
```

Specifically, I have a bit of pyscript that does the following:

```python
wait_kwargs = {}
wait_kwargs["state_check_now"] = True
wait_kwargs["state_trigger"] = f'{entity_id} == "on"'
wait_kwargs["timeout"] = on_timeout_secs
trig_info = task.wait_until(**wait_kwargs)

current_state = state.get(entity_id)
current_attrs = state.getattr(entity_id)
```

The lights only really seem to hang when they're in color mode. `color_temp` mode seems to operate much more smoothly. My lights are the GU10 Phillips Wiz RGB/Kelvin bulbs.

**Comment by sbidy** [comment] 2021-07-11 11:17
I can't reproduce this issue in my test lap.
Appears this error only on one bulb or on everyone in your setup? The exceptions shows a connection issue but if all other requests are working it seems to be an issue with the bulb itself. Do you try a cold reboot oft the bulb?

**Comment by bdraco** [comment] 2022-02-15 20:30
This can be closed as its fixed in the core version

**Closed** 2022-02-15 21:21 UTC
Labels: Bug, No Feedback
